#include "exception.hpp"

void a() {
}